---
name: Publish containers

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Base Images > Generate Tags
        run: ./generate_tags.sh
        working-directory: base

      - name: Base Images > Docker Build Tags
        run: ./docker_tags.sh
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: base

      - name: Base Images > Docker Build & Push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: ./docker_tags.sh -p
        working-directory: base

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker images
        run: ./prestashop_docker.py --quiet tag build

      - name: Push Docker images
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: ./prestashop_docker.py --quiet tag push
